FROM php:7.3-apache

### DEFINE PASTA DOCUMENT_ROOT ###
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

WORKDIR /var/www/html

### INSTALA EXTENSAO DO MONGODB ###
RUN apt-get update \
    && apt-get install -y --no-install-recommends openssl libssl-dev libcurl4-openssl-dev \
    && pecl install mongodb \
    && cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini \
    && echo "extension=mongodb.so" >> /usr/local/etc/php/php.ini \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

### INSTALA COMPOSER ###
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# INSTALA DEPENDENCIAS PRA RODAR COMPOSER
RUN apt-get update && apt-get install -y \
    zlib1g-dev \
    libzip-dev \
	unzip

### INSTALA EXTENSOES E MODULOS NECESSARIOS ###
RUN a2enmod rewrite
RUN docker-php-ext-install zip
RUN docker-php-ext-install bcmath
RUN docker-php-ext-install pdo_mysql

### INSTALA XDEBUG ###
RUN pecl install xdebug

### COPIA ARQUIVOS DO PROJETO NO HOST ###
# ESTA EXECUTANDO NO SETUP #
# COPY api-v2 /var/www/html # 

### RODA COMPOSER INSTALL ###
# RUN composer install --prefer-dist && composer dump-autoload

### AJUSTE DA HORA ###
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone