FROM php:7.3-apache

### DEFINE PASTA DOCUMENT_ROOT ###
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

WORKDIR /var/www/html

### INSTALA E CONFIGURA EXTENSOES E MODULOS NECESSARIOS ###

### INSTALA EXTENSAO DO MONGODB ###
RUN apt-get update \
    && apt-get install -y --no-install-recommends openssl libssl-dev libcurl4-openssl-dev \
    && pecl install mongodb \
    && cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini \
    && echo "extension=mongodb.so" >> /usr/local/etc/php/php.ini \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

### INSTALA EXTENSOES E MODULOS NECESSARIOS ###
RUN a2enmod rewrite

### INSTALA XDEBUG - 5.6 ###
RUN touch /var/log/xdebug.log
RUN pecl install xdebug-2.9.6

### AJUSTE DA HORA ###
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone