FROM php:7.3-apache

### DEFINE PASTA DOCUMENT_ROOT ###
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

WORKDIR /var/www/html

### INSTALA E CONFIGURA EXTENSOES E MODULOS NECESSARIOS ###
RUN apt-get update && apt-get install -y \
    zlib1g-dev \
    libzip-dev \
	unzip
	libjpeg62-turbo-dev \
    libpng-dev \
RUN docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
    && docker-php-ext-install gd mysqli opcache
RUN a2enmod rewrite
RUN docker-php-ext-install zip
RUN docker-php-ext-install pdo_mysql

### INSTALA EXTENSAO DO MONGODB ###
RUN apt-get update \
    && apt-get install -y --no-install-recommends openssl libssl-dev libcurl4-openssl-dev git \
    && pecl install mongodb \
    && cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini \
    && echo "extension=mongodb.so" >> /usr/local/etc/php/php.ini \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

### INSTALA COMPOSER ###
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

### INSTALA XDEBUG ###
RUN touch /var/log/xdebug.log
RUN pecl install xdebug
RUN echo "zend_extension=xdebug.so" >> /usr/local/etc/php/php.ini

### AJUSTE DA HORA ###
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone